CREATE TABLE a
(
    id  VARCHAR(45) PRIMARY KEY,
    foo VARCHAR(45) NOT NULL,
    b_id VARCHAR(45)
);

CREATE TABLE b
(
    id  VARCHAR(45) PRIMARY KEY,
    foo VARCHAR(45) NOT NULL,
    c_id VARCHAR(45)
);

CREATE TABLE c
(
    id  VARCHAR(45) PRIMARY KEY,
    foo VARCHAR(45) NOT NULL
);

ALTER TABLE a ADD FOREIGN KEY (b_id) REFERENCES b(id);
ALTER TABLE b ADD FOREIGN KEY (c_id) REFERENCES c(id);

